### ISSUE TITLE
hi  i did't see the  Decoding code,  will you add some?

### ISSUE THREAD

**Issue by notedit** [twenty-zp/RealTimeAVVideo#1]

**Comment by twenty-zp** [comment]
对于解码你可以看[H264DecodeDemo源码](https://github.com/ChenYongJunM/H264DecodeDemo),而我解码根据此修改[How to use VideoToolbox to decompress H.264 video stream](http://stackoverflow.com/questions/29525000/how-to-use-videotoolbox-to-decompress-h-264-video-stream?noredirect=1&lq=1),因此并未上传demo中,同时你也可以查询ffmpeg 解码H264文件,当然如果你要查看自己的H264文件,可以使用[VLC](http://www.videolan.org/)进行播放

**Comment by notedit** [comment]
thanks.  我想写一个简单的rtsp的播放器,用videoToolbox   不知道你有没有兴趣

**Comment by twenty-zp** [comment]
硬编解码我也是最近刚开始研究学习,所以也是知之甚少,如果你要是想自己写一个的话,其实可以参考github中已有的那些类库,rtsp、rtmp协议都有。FFMPEG 可参考[雷霄骅(leixiaohua1020)的专栏](http://blog.csdn.net/leixiaohua1020/article/details/15811977)

**Comment by notedit** [comment]
ffmpeg 依赖太多  我需要小巧  可以多播  延时小的播放器
