### ISSUE TITLE
请问怎么修改配置实现在横屏LandscapeRight 状态下拍摄 640x480分辨率 视频

### ISSUE THREAD

**Issue by LemonChao** [twenty-zp/RealTimeAVVideo#2]
必须要特别感谢你的无私分享，帮我解决了燃眉之急。
但我在横屏LandscapeRight 状态下拍摄 640x480 视频时，遇到了困难
1.我把 `videoSize = CGSizeMake(480, 640)`修改成`videoSize = CGSizeMake(640, 480)`后，分辨率由原来的480x640变成了640x480，不知道这样处理是否合理？？
2.横屏下session.preView 一直是竖屏状态下的frame，即使我强制用代码修改成横屏的frame仍然不见成效。
3.session.preView 显示录制的视频方向也是不正确的
请教一下，如果要在横屏LandscapeRight状态下录制视频，要做哪些修改？？

**Comment by twenty-zp** [comment]
抱歉,RTAVVideoConfiguration.m中的landscape属性,我固定写为NO,你只修改    configuration.landscape = landscape; 即可.

**Comment by LemonChao** [comment]
你好，修改 configuration.landscape = landscape 我注意到了，修改过后，上面的问题2，3仍然存在。。本人多媒体入门级水平，追踪到配置 session 时`[[UIApplication sharedApplication] statusBarOrientation]` 返回为1。可是应用已经处于LandscapeRight，从状态栏的位置可以确信。
2.横屏时上面问题1中，宽高是不是都要调换一下？？
Many Thanks!!

**Comment by twenty-zp** [comment]
@LemonChao  如果你设备支持水平的话,Target-> General->Device Orientation 要选中 Landscape Left 这样的话，输出H264才会正确。 其余的什么都不用改变

**Comment by twenty-zp** [comment]
@LemonChao  640x480是分辨率的意思,和你出来视频的frame没有关系。如果你横屏录制视频，那么你出来的视频也是横屏的,别人看的话,他的手机也要横屏

**Comment by twenty-zp** [comment]
你只需要将你页面中需要显示的布局内容改变即可。如:  聊天内容、礼物、观看头像 再次布局即可。

**Comment by twenty-zp** [comment]
configuration.landscape 如果设置为YES,那么你Xcode中的Target -> Geneal -> Device 要支持Left

**Comment by LemonChao** [comment]
多谢大神指点，这点明白了！！
我的工程Target -> Geneal -> Device Orientation 支持Portrait、Left、Right 三个方向，
发现屏幕在转为横屏时，session的preView并没有跟随控制器的view转到横屏，看到的画面不全，一半是空白的，我在收到的转屏通知里修改preView的frame也没有效果，
请问这个怎么处理才好？？

**Comment by twenty-zp** [comment]
@LemonChao  你的类似点击按钮, 放大旋转全屏播放界面? preView中存在子laye——AVCaptureVideoPreviewLayer. 
  session的preView并没有跟随控制器的view转到横屏： 你要重新布局preView的, 而preView的子layer 大小为 [UIScreen mainScreen].bounds .

**Comment by twenty-zp** [comment]
@LemonChao  你可以将preViewLayer 的设置大小写到 设置preView的时候,设置和preView大小相同。

**Comment by twenty-zp** [comment]
这个并非是个库,只是个学习demo. 如果你正在做正式版本的话,还是使用github上边那些完整的第三方库.

**Comment by LemonChao** [comment]
恩，好的，我再看看，同样谢谢了。
有好的第三方库推荐吗？

**Comment by twenty-zp** [comment]
https://github.com/ksvc/KSYLive_iOS     
https://github.com/runner365/LiveVideoCoreSDK
https://github.com/LaiFengiOS/LFLiveKit  
七牛直播SDK
...
还有一些coreVideo, 你都可以看看

**Comment by LemonChao** [comment]
多谢！多谢！
